### ISSUE TITLE
In android os 9 device "com.emerchantpay.gateway.genesisandroid.api.exceptions.UnexpectedException: Connection closed by peer

### ISSUE THREAD

**Issue by kazimdsaidul** [GenesisGateway/android_sdk#1]
*In android os 9 device "com.emerchantpay.gateway.genesisandroid.api.exceptions.UnexpectedException: Connection closed by peer"*

**In android os 9 device "com.emerchantpay.gateway.genesisandroid.api.exceptions.UnexpectedException: Connection closed by peer**

**Steps to Reproduce**

eMerchantPaymentManager.makePayment(
                    requireActivity(),
                    topUpPaymentMethodState.transactionId,
                    topUpPaymentMethodState.amountToBePaid,
                    topUpPaymentMethodState.consumerId,
                    getString(R.string.top_up),
                    onCallback = { title, content ->
                        showAlertDialog(title, content)
                    }
                )

**Expected Results**
   Get response or error 

**Actual Results**
 No response or error just logcat show om.emerchantpay.gateway.genesisandroid.api.exceptions.UnexpectedException: Connection closed by peer

**Comment by plpt88** [comment]
Hello @kazimdsaidul ,

Thank you for the reported issue. We will check it.

**Comment by kazimdsaidul** [comment]
Thanks for your response. If need any additional information, please let me know.

**Comment by kazimdsaidul** [comment]
<img width="941" alt="Screenshot 2023-05-30 at 11 21 59 PM" src="https://github.com/GenesisGateway/android_sdk/assets/7722028/1e308b6e-5b64-4ac7-bcc5-3a10d6ae8fe1">

@plpt88. I think need a throw Exception client.

**Comment by plpt88** [comment]
@kazimdsaidul,

We are preparing a new release with the updates. FYI we've missed in some places to throw a correct error.
We'll ping you when we publish the release.

**Comment by kazimdsaidul** [comment]
@plpt88 Thanks. please give a release as soon as possible. we are blocking for this. Another issue is that today auto disable debug in Android and UI does not respond when a call started from the **Configuration** constructor call.  Why can't debug?

**Comment by plpt88** [comment]
@kazimdsaidul,
About debugging it depends on many things from Run/Debug configurations, how is setup etc.
Please restart Android Studio and rebuild your project.

**Comment by kazimdsaidul** [comment]
@plpt88, 

I think you also face this issue just create an emulator on Android 9 and breakpoint on [java/com/merchantman/gateway/genesis android/api] under any class.

**Comment by plpt88** [comment]
Hello @kazimdsaidul,

We have a new version:

<a href="https://github.com/GenesisGateway/android_sdk/releases/tag/1.3.7">GitHub tag 1.3.7</a>

UnexpectedException was handled properly.
About debugging we'll investigate further in details, if we found some issues we'll fix them.
If you have any issues, let us know. Closing this one.

**Comment by kazimdsaidul** [comment]
Yes. But 1.3.6. also same in android of same.
