### ISSUE TITLE
in 1.3.7 release: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.toString()' on a null object reference 

### ISSUE THREAD

**Issue by kazimdsaidul** [GenesisGateway/android_sdk#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.toString()' on a null object reference 

OS = only Android 9 
SDK version: 1.3.7 

**This is for bugs**
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.toString()' on a null object 

ErrorCodes.SYSTEM_ERROR.code = 100

**Steps to Reproduce**

fun makePayment(
        activity: Activity,
        transactionId: String,
        amountToBePaid: String,
        consumerId: String,
        paymentUsage: String,
        onCallback: (title: String, content: String) -> Unit
    ) {
        try {
            val configuration = Configuration(
                BuildConfig.E_MERCHANT_USER_NAME,
                BuildConfig.E_MERCHANT_PASSWORD,
                Environments.STAGING,
                Endpoints.EMERCHANTPAY,
                Locales.EN
            ).apply {
                tokenEnabled = true
                token = BuildConfig.E_MERCHANT_TOKEN
                if (BuildConfig.DEBUG) {
                    setDebugMode(true)
                }
            }

            val paymentRequest = PaymentRequest(
                context = activity,
                transactionId = transactionId,
                amount = BigDecimal(amountToBePaid),
                currency = Currency.GBP,
                customerEmail = preferenceHelper.email,
                customerPhone = preferenceHelper.mobileNumber.ifEmpty { "" },
                billingAddress = PaymentAddress(
                    firstName = preferenceHelper.firstName,
                    lastname = preferenceHelper.firstLastName,
                    address1 = preferenceHelper.houseNo.ifEmpty { preferenceHelper.houseName },
                    address2 = preferenceHelper.streetName,
                    zipCode = preferenceHelper.postCode,
                    city = preferenceHelper.cityOrTown,
                    state = preferenceHelper.country,
                    country = getCountryData() ?: Country.UnitedKingdom
                ),
                notificationUrl = "https://abc.com",
                transactionTypes = TransactionTypesRequest().apply {
                    addTransaction(WPFTransactionTypes.SALE)
                }
            ).apply {
                setLifetime(60)
                setRememberCard(rememberCard = true)
                setUsage(paymentUsage)
                setConsumerId(consumerId)
            }

            val genesis = Genesis(
                activity,
                configuration,
                paymentRequest
            )

            when {
                !genesis.isConnected(activity)!! -> onCallback(
                    activity.getString(R.string.error_),
                    ErrorMessages.CONNECTION_ERROR
                )
                genesis.isConnected(activity)!! && genesis.isValidData!! -> {
                    genesis.push()
                    val response = genesis.response
                    when {
                        !response?.isSuccess!! -> {
                            error = response.error
                            onCallback(
                                activity.getString(R.string.error_),
                                error?.message ?: activity.getString(R.string.warn_some_error)
                            )
                        }
                    }
                }
                !genesis.isValidData!! -> {
                    error = genesis.error
                    val message = error!!.message
                    val technicalMessage =
                        if (error!!.technicalMessage != null && error!!.technicalMessage!!.isNotEmpty()) error!!.technicalMessage
                        else ""
                    onCallback(
                        activity.getString(R.string.invalid_),
                        "$technicalMessage $message"
                    )
                }
            }
        } catch (e: Exception) {
            Timber.e("Exception in EMerchantPaymentManager ${e.message}")
            Timber.e("Exception in EMerchantPaymentManager ${e.localizedMessage}")
            Timber.e("Exception in EMerchantPaymentManager ${e.printStackTrace()}")
        }
    }

**Expected Results**
Return proper validation error from server end success or error

**Actual Results**
java.lang.NullPointerException:

**Comment by kazimdsaidul** [comment]
<img width="1214" alt="Screenshot 2023-06-01 at 2 00 13 PM" src="https://github.com/GenesisGateway/android_sdk/assets/7722028/9404a8f0-a315-4d02-8f9c-79d3d181adfe">

**Comment by plpt88** [comment]
Hello @kazimdsaidul ,

Thank you for the reported issue. We will check it and prepare a release with the fix.

**Comment by plpt88** [comment]
Hello @kazimdsaidul,

We have a new version:

<a href="https://github.com/GenesisGateway/android_sdk/releases/tag/1.3.8">GitHub tag 1.3.8</a>

UnexpectedException was handled properly.
If you have any issues, let us know. Closing this one.

**Comment by kazimdsaidul** [comment]
@plpt88 I tes 1.3.8 but still not working in android 9. 

javax.net.ssl.SSLHandshakeException: Connection closed by peer

<img width="1256" alt="Screenshot 2023-06-08 at 11 41 46 AM" src="https://github.com/GenesisGateway/android_sdk/assets/7722028/81c73ed5-934f-4ad6-a725-03107b81a0b6">
<img width="978" alt="Screenshot 2023-06-08 at 11 41 55 AM" src="https://github.com/GenesisGateway/android_sdk/assets/7722028/3fa63786-ce35-4d70-a6a8-3caafe2fcae5">
