### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Connection closed by peer in android 9 OS

### ISSUE THREAD

**Issue by kazimdsaidul** [GenesisGateway/android_sdk#4]
javax.net.ssl.SSLHandshakeException: Connection closed by peer in android 9 OS

<img width="1256" alt="Screenshot 2023-06-08 at 11 41 46 AM" src="https://github.com/GenesisGateway/android_sdk/assets/7722028/4df2671d-9ada-4f33-9025-c97630fbeb66">
<img width="978" alt="Screenshot 2023-06-08 at 11 41 55 AM" src="https://github.com/GenesisGateway/android_sdk/assets/7722028/5def882e-08c2-4fc6-a951-1f9960d7c51c">

**Comment by plpt88** [comment]
Hello @kazimdsaidul,

Thank you for the reported issue. This occurs only on Android 9/API level 28.
We'll investigate and prepare a release with the fix.

**Comment by plpt88** [comment]
Hello @kazimdsaidul,

We have a new version with latest fixes:

<a href="https://github.com/GenesisGateway/android_sdk/releases/tag/1.3.9">GitHub tag 1.3.9</a>

SSLHandshakeException has fixed already.
If you have any issues, let us know. Closing this one.

**Comment by kazimdsaidul** [comment]
@plpt88 Thanks. It is working.
